Convert query result to array
The collection needs to be converted to an array, otherwise line 37 would raise `NoMethodError (undefined method `concat' for an instance of ActiveRecord::Relation)`.